package com.ruiniles.glucoview.presentation.util

object TestTag {
    const val DASHBOARD_SCREEN = "DASHBOARD_SCREEN"
    const val LOAD_FILE_SCREEN = "LOAD_FILE_SCREEN"
    const val LOAD_FILE_TITLE = "LOAD_FILE_TITLE"
    const val LOAD_FILE_PROMPT = "LOAD_FILE_PROMPT"
    const val SELECT_FILE_BUTTON = "SELECT_FILE_BUTTON"
    const val FILE_TEXT_PREVIEW = "FILE_TEXT_PREVIEW"
    const val NEXT_BUTTON = "NEXT_BUTTON"
    const val MORE_BUTTON = "MORE_BUTTON"
    const val RESET_BUTTON = "LOGOUT_BUTTON"
    const val GLUCOSE_READING_VALUE_TEXT = "GLUCOSE_LEVEL_TEXT"
    const val GLUCOSE_READING_UNIT_TEXT = "GLUCOSE_LEVEL_UNIT_TEXT"
    const val GLUCOSE_READING_TREND_ARROW = "GLUCOSE_LEVEL_TREND_ARROW"
    const val GLUCOSE_READING_TIMESTAMP_TEXT = "GLUCOSE_LEVEL_TIMESTAMP_TEXT"
    const val CONSOLE_LOG = "CONSOLE_LOG"
    const val CLEAR_BUTTON = "CLEAR_BUTTON"
}